### ISSUE TITLE
Rails attachment problems with jruby >= jruby-9.4.4.0 

### ISSUE THREAD

**Issue by jlahtinen** [ruby/strscan#92]
Rails fails when uploaded file is binary type like PDF.

Failing row is https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/multipart/parser.rb#L414

```
invalid byte sequence in UTF-8org/jruby/RubyString.java:2943:in `sub!'
org/jruby/RubyString.java:2923:in `sub'
/usr/share/tomcat9/sikke_apps/ROOT/WEB-INF/gems/gems/rack-2.2.8.1/lib/rack/multipart/parser.rb:284:in `handle_mime_body'
/usr/share/tomcat9/sikke_apps/ROOT/WEB-INF/gems/gems/rack-2.2.8.1/lib/rack/multipart/parser.rb:226:in `block in run_parser'
```

I was not able to make a simple case that failed with 9.4.4.0 but not with 9.4.3.0. I was able to make a simple test that "worked" with 9.4.3.0 but not with 9.4.4.0:

```
require 'strscan'

t = "%PDF-1.7\n%\xE2\xE3\xCF\xD3\n85"

ss = StringScanner.new ""
ss.concat t

s = ss.check_until /5/

print s
```

@headius do you have any idea what to try/fix to make Rails work with jruby >= 9.4.4.0 and multipart binary uploads.

I also noticed that if I change line

`body = body_with_boundary.sub(@body_regex_at_end, '') # remove the boundary from the string`

with

`body = body_with_boundary.force_encoding("BINARY").sub(@body_regex_at_end, '') # remove the boundary from the string`

PDF file upload starts to work again, but I am not sure why it worked with 9.4.3.0 and most probably works with cruby also.

**Comment by headius** [comment]
Good find! We should be able to investigate this and get a strscan release out. Hopefully this is the only thing preventing multi-part posts.

I'm guessing you could probably narrow this down to a specific release of strscan since I have been doing a bunch of small compatibility and performance patches recently.

**Comment by headius** [comment]
Full backtrace on JRuby 9.47.0-SNAPSHOT (master):

```
[] jruby $ jruby -Xbacktrace.style=full blah.rb
ArgumentError: invalid byte sequence in UTF-8
             getStackTrace at java/lang/Thread.java:2450
          getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:269
              getBacktrace at org/jruby/runtime/backtrace/TraceType.java:54
          captureBacktrace at org/jruby/RubyException.java:434
                  preRaise at org/jruby/exceptions/RaiseException.java:217
                    <init> at org/jruby/exceptions/RaiseException.java:65
                    <init> at org/jruby/exceptions/Exception.java:39
                    <init> at org/jruby/exceptions/StandardError.java:38
                    <init> at org/jruby/exceptions/ArgumentError.java:38
        constructThrowable at org/jruby/RubyArgumentError.java:58
               toThrowable at org/jruby/RubyException.java:396
                      from at org/jruby/exceptions/RaiseException.java:94
         newRaiseException at org/jruby/Ruby.java:4303
          newArgumentError at org/jruby/Ruby.java:3580
           prepareEncoding at org/jruby/RubyRegexp.java:392
            preparePattern at org/jruby/RubyRegexp.java:415
                      scan at org/jruby/ext/strscan/RubyStringScanner.java:289
               check_until at org/jruby/ext/strscan/RubyStringScanner.java:431
                      call at org/jruby/ext/strscan/RubyStringScanner$INVOKER$i$1$0$check_until.gen:-1
              cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:466
                      call at org/jruby/runtime/callsite/CachingCallSite.java:244
  invokeOther3:check_until at blah.rb:8
                    <main> at blah.rb:8
                       run at blah.rb:-1
       invokeWithArguments at java/lang/invoke/MethodHandle.java:733
                      load at org/jruby/ir/Compiler.java:114
                 runScript at org/jruby/Ruby.java:1245
               runNormally at org/jruby/Ruby.java:1157
               runFromMain at org/jruby/Ruby.java:983
             doRunFromMain at org/jruby/Main.java:398
               internalRun at org/jruby/Main.java:282
                       run at org/jruby/Main.java:227
                      main at org/jruby/Main.java:199
```

This is running with latest strscan.

**Comment by headius** [comment]
Looks like the incoming string is getting marked as "broken" because this test triggers the error:

https://github.com/jruby/jruby/blob/a37fb3ff9b24e50bb75a558433b26d333cbb3188/core/src/main/java/org/jruby/RubyRegexp.java#L391-L393

**Comment by headius** [comment]
@jlahtinen It seems like CRuby also fails on this script:

```
$ ruby33 blah.rb
blah.rb:8:in `check_until': invalid byte sequence in UTF-8 (ArgumentError)

s = ss.check_until /5/
                   ^^^
	from blah.rb:8:in `<main>'
```

I believe your example may be a red herring, or at least is not demonstrating an actual bug. The string **is** broken if treated as UTF-8, so this is probably expected behavior.

**Comment by jlahtinen** [comment]
@headius yeah I think also that my example was good enough to demonstrate the actual problem I have. But it was something that I found that works differently between jruby 9.4.3.0 and jruby 9.4.4.0.

I continue investigating and trying to understand what is the actual problem.

**Comment by jlahtinen** [comment]
Jruby 9.4.6.0 with strscan 3.0.8 seems to be working (only change).

With 3.1.0 binary files in POST requests do not work (original issue here).
With 3.0.9 there are even more weird problems and it seems that rails can not render any page.

I'll continue to investigate what happens between 3.0.8 and 3.0.9

**Comment by jlahtinen** [comment]
I forgot to mention that this problem exists when running in tomcat9 (production like environment) but not when running on rails development environment inside puma.

**Comment by jlahtinen** [comment]
I noticed that when running inside puma line https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/multipart/parser.rb#L413 gives back string (body_with_boundary) with **binary** encoding but inside tomcat it gives back string with UTF-8 encoding.

**Comment by jlahtinen** [comment]
https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/multipart/parser.rb#L261 content here in tomcat and in puma is binary (ASCII-8BIT)

For some reason it converts from binary to utf8 inside StringScanner if I understand correctly.

**Comment by headius** [comment]
So this is *only* happening when running in Tomcat? That might point to a bug in jruby-rack, only now exposed by StringScanner because we started checking encoding stuff.

**Comment by jlahtinen** [comment]
Any comments about the fact that in line https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/multipart/parser.rb#L261 content encoding in puma and tomcat9 is ASCII-8BIT

But in tomcat9 https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/multipart/parser.rb#L413 check_until returns string in UTF-8. Running with Puma check_until returns in ASCII-8BIT.

Is there some default encoding or something that is set differently in tomcat9 vs Puma?

**Comment by jlahtinen** [comment]
To make this clearer:

I modified line https://github.com/rack/rack/blob/e83001100ad9dd24e1744b13669dcb2736a13ebd/lib/rack/multipart/parser.rb#L200

(gem version 2.2.8.1)

to

        puts "#" * 80
        puts content.encoding
        puts "".dup.encoding
        @sbuf.concat content
        puts @sbuf.scan(/.*/).encoding
        puts "#" * 80


With puma this prints

################################################################################
ASCII-8BIT
UTF-8
ASCII-8BIT
################################################################################

and with tomcat9

################################################################################
ASCII-8BIT
UTF-8
UTF-8
################################################################################


I can't figure out why StringReader changes encoding inside tomcat9 but on inside puma. For me this does not look like jruby-rack problem. Any idea @headius ?

**Comment by jlahtinen** [comment]
Updated title to match reality. Works with jruby < 9.4.6.0 inside puma and tomcat9

**Comment by headius** [comment]
I'll try to figure this out today.

**Comment by headius** [comment]
A quick search of jruby-rack and warbler code found no instances of "ASCII" or "BINARY" that might be setting encoding as such.

**Comment by headius** [comment]
@jlahtinen Can you put together a repo that demonstrates this in a very simple app? If you can do that I can probably find the problem and fix it pretty quickly.

**Comment by jlahtinen** [comment]
@headius I was able to create a minimal rails project. I hope this is simple enough.

https://github.com/jlahtinen/strscan-bin-app

Works inside puma but inside tomcat9:
![image](https://github.com/ruby/strscan/assets/15891552/38c9e452-6fd5-4a8a-ac0f-e0bd1379f9a2)

**Comment by jlahtinen** [comment]
@headius here is sample app without rails

https://github.com/jlahtinen/jruby-rack-example

**Comment by headius** [comment]
I was able to reproduce with Tomcat and your latest example.

**Comment by headius** [comment]
Ok I have a debugger stopped at the creation of the ArgumentError and it seems like it's sort-of the opposite of what we thought.

The logic here is attempting to do a Regexp match against a String. The String contains the PDF data, which is basically binary, but it is marked as UTF-8 encoding. That results in the error, because it checks whether the string has valid UTF-8 data and hits various bits in the PDF that are just binary chunks.

So the question is how to get that PDF data into the system without it being marked as UTF-8.

**Comment by headius** [comment]
The logic that eventually fails in is rack/multipart/parser.rb in the `handle_mime_body` method:

```ruby
        if (body_with_boundary = @sbuf.check_until(@body_regex)) # check but do not advance the pointer yet
          body = body_with_boundary.sub(/#{@body_regex}\z/m, '') # remove the boundary from the string
          @collector.on_mime_body @mime_index, body
```

Here the `check_until` returns the binary data marked as UTF-8.

The `@sbuf` is a StringScanner created earlier in the file as follows:

```ruby
@sbuf = StringScanner.new("".dup)
```

And data is appended to it via `concat` as here in `read_data`:

```ruby
      def read_data(io, outbuf)
        content = io.read(@bufsize, outbuf)
        handle_empty_content!(content)
        @sbuf.concat(content)
      end
```

If the data from `io.read` is binary but coming back as UTF-8. That could cause this. If not, then perhaps appending BINARY content to a UTF-8 StringScanner is keeping it as UTF-8.

**Comment by headius** [comment]
Based on the above information, I'm going with the theory that StringScanner is stuffing binary data into a UTF-8 buffer without marking as BINARY, which eventually breaks this:

```
$ jruby -rstrscan -e 'ss = StringScanner.new("".dup); ss.concat("\xc3\x28\0"); str = ss.check_until(/\0/); p str.encoding; str.sub(/foo/, "")'
ArgumentError: invalid byte sequence in UTF-8
         scan at org/jruby/ext/strscan/RubyStringScanner.java:289
  check_until at org/jruby/ext/strscan/RubyStringScanner.java:431
       <main> at -e:1
```

This logic actually produces an error in CRuby, but at the point of calling `check_until`:

```
$ ruby31 -rstrscan -e 'ss = StringScanner.new("".dup); ss.concat("\xc3\x28\0"); str = ss.check_until(/\0/); p str.encoding; str.sub(/foo/, "")'
-e:1:in `check_until': invalid byte sequence in UTF-8 (ArgumentError)
	from -e:1:in `<main>'
```

**Comment by headius** [comment]
Getting closer...

It does appear that strscan in JRuby will properly switch the encoding to BINARY if the incoming data is BINARY, and IO read operation here is returning BINARY. But stepping through the actual `concat` logic shows that although the data is marked as BINARY, it also has a code range of "CR_7BIT" and the logic we have for concatenation then assumes it can safely be "updated" to the existing UTF-8 encoding.

I believe this is the root of the problem, but I am not sure how this clearly-binary string is getting marked as 7-bit ASCII.

**Comment by headius** [comment]
I think this might be the problematic line:

https://github.com/jruby/jruby-rack/blob/4b89fa75144ac398f2a9825103ec9144ebe4bf63/src/main/java/org/jruby/rack/ext/Input.java#L146

This logic wraps the servlet IO with our own `JRuby::Rack::Input`. The code here is for reading data off the wire, and in this particular case it is reading into a given buffer create with `String.new` which produces a String with a code range of `CR_7BIT`.

The `cat` call here is an old version that does not take into consideration encodings or code ranges or any of that stuff. It just slams the incoming bytes directly onto the existing buffer.

In this case, it's taking data off the wire that is marked as binary, shoving it into the buffer, and leaving the encoding as UTF-8 and the code range as CR_7BIT, which breaks the string and eventually leads to errors when those things become important (as in the StringScanner logic).

**Comment by headius** [comment]
The good news is that a quick tweak to that line of code fixes your case!

The bad news is that jruby-rack has not had a new build in many, many years, and some of the tooling used for that build also needs to be updated. I'm working on that now.

**Comment by headius** [comment]
I should have done this a while ago, but this is not a bug in strscan. It is a bug in how jruby-rack concatenates incoming bytes onto the Rack buffer, which broke the string's encoding.

I am closing this as invalid and will open a new issue on jruby-rack shortly.
